#!/usr/bin/env python3
"""Render trusted wiki references and coverage from checked-in sources.

No network, raw archive, or third-party Python dependency is required. Editorial
changes belong in sources/wiki-content.json or sources/wiki-tables/*.json.
"""
from __future__ import annotations

import argparse
from collections import Counter
import json
import os
import re
from pathlib import Path
import sys

from wiki_archive_bundle import render_archive, validate_snapshot, quote_source

ROOT = Path(__file__).resolve().parents[1]
BASE = Path('skills/overwatch-workshop/references/wiki')
GENERATED = '<!-- Generated by scripts/generate-wiki.py; edit normalized sources. -->'
RETAINED = {'rewritten', 'consolidated', 'historical', 'source', 'removed'}


def load(path):
    return json.loads((ROOT / path).read_text(encoding='utf-8'))


def link_from(path, destination):
    target, separator, anchor = str(destination).partition('#')
    relative = os.path.relpath(target, Path(path).parent).replace(os.sep, '/')
    return relative + (separator + anchor if separator else '')


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ').replace('<', '&lt;').replace('>', '&gt;')


def validate(data, tables):
    articles = data['articles']
    if len(articles) != data['snapshot']['article_count']:
        raise ValueError('Article count does not match reviewed snapshot')
    if sum(len(a['notes']) for a in articles) != data['snapshot']['survey_note_count']:
        raise ValueError('Note count does not match reviewed snapshot')
    ids = [a['id'] for a in articles]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate article IDs')
    note_ids = []
    for a in articles:
        if a['review_status'] not in ('read', 'synced'):
            raise ValueError(f"Unreviewed article {a['id']}")
        if not a.get('reason'):
            raise ValueError(f"Missing disposition reason {a['id']}")
        if a['disposition'] == 'catalog-covered' and not a.get('catalog_destination'):
            raise ValueError(f"Catalog coverage without exact destination {a['id']}")
        for n in a['notes']:
            note_ids.append(n['id'])
            if n['id'] != f"wiki-{a['id']}-n{n['survey_note']}":
                raise ValueError(f"Unstable note ID {n['id']}")
            if n['disposition'] in RETAINED and not n.get('destination'):
                raise ValueError(f"Retained note without destination {n['id']}")
            if n['disposition'] not in RETAINED and not n.get('reason'):
                raise ValueError(f"Omitted note without reason {n['id']}")
            if not n.get('text') or not n.get('source_location') or not n.get('evidence_status'):
                raise ValueError(f"Incomplete claim {n['id']}")
    if len(note_ids) != len(set(note_ids)):
        raise ValueError('Duplicate note IDs')
    for t in tables:
        if t['source_article_id'] not in ids:
            raise ValueError('Table has no article provenance')
        for table in t['tables']:
            if t.get('source_backed'):
                continue
            if not table['columns'] or not table['rows']:
                raise ValueError(f"Empty table {table['id']}")
            if any(len(r) != len(table['columns']) for r in table['rows']):
                raise ValueError(f"Unequal table width {table['id']}")


def render_topic(topic, info, articles, path):
    parts = [GENERATED, f"# {info['title']}", info['read_when'],
             'Select the relevant entry. Each entry links to its trusted local wiki source.',
             '## Entries']
    parts += [f"- [{a['title']}]({link_from(path, a['destination'])})" for a in sorted(articles, key=lambda a: a['title'].casefold())]
    return '\n\n'.join(parts)+'\n'


def render_article(a, path, source=None):
    source_id = source['id'] if source else a['id']
    parts = [GENERATED, f'<a id="wiki-{a["id"]}"></a>', f"# {a['title'].rstrip()}",
              f"Source: [wiki article {source_id}]({link_from(path, BASE/'archive'/(str(source_id)+'.md'))}); edited {a['source_updated_at'][:10]}." ]
    if a.get('source_backed'):
        parts += [f'<a id="{n["id"]}"></a>' for n in a['notes']]
        if source is None:
            parts.append('This article is no longer present in the current wiki snapshot.')
        else:
            parts += ['## Current wiki text', quote_source(source['content'])]
        return '\n\n'.join(parts)+'\n'
    if a.get('catalog_destination'):
        parts.append(f"Exact pinned API: [{a['title']}]({link_from(path, a['catalog_destination'])}).")
    if a.get('api_summary'):
        parts.append(a['api_summary'])
    for n in a['notes']:
        if (n.get('destination') or '').split('#')[0] != str(path):
            continue
        parts += [f'<a id="{n["id"]}"></a>', f"- {n['text']}"]
    if a['tables']:
        parts += [f"Data: [normalized factual tables]({link_from(path, a['tables'][0])})."]
    if a.get('omitted_material'):
        parts += ['Offline scope: '+m['reason'] for m in a['omitted_material']]
    return '\n\n'.join(parts)+'\n'


def source_table(record, article, source, path, anchors):
    parts = [GENERATED, f"# {record['title']}"]
    parts += [f'<a id="{anchor}"></a>' for anchor in anchors]
    if source is None:
        parts.append('This article is no longer present in the current wiki snapshot.')
    else:
        parts += [f"Source: [current wiki article]({link_from(path, BASE/'archive'/(str(source['id'])+'.md'))}); edited {source['updated_at'][:10]}.",
                  quote_source(source['content'])]
    return '\n\n'.join(parts)+'\n'


def render_table(record, article, source=None):
    path = record['destination']
    if record.get('source_backed'):
        return source_table(record,article,source,path,[t['id'] for t in record['tables']])
    parts = [GENERATED, f"# {record['title']}",
             f"Source: [{article['title']}]({link_from(path, BASE/'archive'/(str(article['id'])+'.md'))}); page edited {article['source_updated_at'][:10]}.",
             f"Read [behavior and limitations]({link_from(path, article['destination'])}) before using these values."]
    parts += record['context']
    parts += ['## Contents']
    parts += [f"- [{t['title']}]({link_from(path, t['destination']) if t.get('destination') else '#'+t['id']})" for t in record['tables']]
    for table in record['tables']:
        if table.get('destination'):
            continue
        parts += [f'<a id="{table["id"]}"></a>', f"## {table['title']}"]
        lines = ['| '+' | '.join(cell(v) for v in table['columns'])+' |',
                 '| '+' | '.join('---' for _ in table['columns'])+' |']
        lines += ['| '+' | '.join(cell(v) for v in row)+' |' for row in table['rows']]
        parts.append('\n'.join(lines))
    return '\n\n'.join(parts)+'\n'


def render_table_part(record, article, table, source=None):
    path = table['destination']
    if record.get('source_backed'):
        return '\n\n'.join([GENERATED, f"# {record['title']}: {table['title']}",
            f'<a id="{table["id"]}"></a>',
            f"Read the [current wiki tables and their conditions]({link_from(path,record['destination'])}). This local path remains available for existing references."])+'\n'
    parts = [GENERATED, f"# {record['title']}: {table['title']}",
             f"Wiki data from [article {article['id']}]({link_from(path, BASE/'archive'/(str(article['id'])+'.md'))}); page edited {article['source_updated_at'][:10]}.",
             f"Read [units, scope and source limitations]({link_from(path, record['destination'])}) before using these values.",
             f'<a id="{table["id"]}"></a>']
    rows = ['| '+' | '.join(cell(v) for v in table['columns'])+' |',
            '| '+' | '.join('---' for _ in table['columns'])+' |']
    rows += ['| '+' | '.join(cell(v) for v in row)+' |' for row in table['rows']]
    parts += ['\n'.join(rows)]
    return '\n\n'.join(parts)+'\n'


def coverage(data, tables):
    result = {'schema_version': 1, 'snapshot': data['snapshot'],
              'article_count': len(data['articles']), 'note_count': sum(len(a['notes']) for a in data['articles']),
              'article_dispositions': dict(sorted(Counter(a['disposition'] for a in data['articles']).items())),
              'note_dispositions': dict(sorted(Counter(n['disposition'] for a in data['articles'] for n in a['notes']).items())),
              'table_files': len(tables), 'table_rows': sum(len(t['rows']) for r in tables for t in r['tables']), 'articles': []}
    for a in data['articles']:
        entry = {k: a[k] for k in ('id', 'title', 'source_url', 'source_updated_at', 'source_content_sha256', 'disposition', 'reason')}
        entry.update({k:a[k] for k in ('source_revision_id','source_backed','source_missing','revision_ids') if k in a})
        entry['destinations'] = list(dict.fromkeys(d for d in [a.get('destination'), a.get('catalog_destination'), *a['tables']] if d))
        entry['notes'] = [{k: n[k] for k in ('id', 'survey_note', 'disposition', 'evidence_status', 'destination')}
                          | ({'reason': n['reason']} if n.get('reason') else {})
                          | ({'related_destinations': n['related_destinations']} if n.get('related_destinations') else {})
                          for n in a['notes']]
        if a.get('omitted_material'):
            entry['omitted_material'] = a['omitted_material']
        result['articles'].append(entry)
    return json.dumps(result, ensure_ascii=False, indent=2)+'\n'


def render(data, tables, snapshot):
    output = {}; articles = data['articles']; by_id = {a['id']: a for a in articles}
    sources = {a['id']: a for a in snapshot['articles']}
    index = [GENERATED, '# Archived Workshop behavior notes',
             'Open only the topic that matches the current task. These supplements retain wiki-specific exceptions and measured data; ordinary API signatures live in the pinned API catalog.',
             'Workshop.codes wiki articles are the trusted source of truth. Maintenance automatically updates these local references from the wiki.',
             f"For original wording or a source omitted from the guides, use the [full local article archive](archive/index.md). All {len(snapshot['articles'])} source articles are installed; open only the relevant article and do not fetch website links.",
             '## Select a topic']
    for topic, info in data['topics'].items():
        path = BASE / (topic+'.md')
        selected = [a for a in articles if a['topic'] == topic and a['disposition'] in RETAINED]
        if not selected:
            continue
        output[path] = render_topic(topic, info, selected, path)
        for article in selected:
            article_path = Path(article['destination'].split('#')[0])
            output[article_path] = render_article(article, article_path, sources.get(article.get('source_revision_id',article['id'])))
        index += [f"- [{info['title']}]({topic}.md) — {info['read_when'].removeprefix('Read for ').removeprefix('Read when ')}"]
    index += ['## Select a factual table', 'These files are optional lookup data. Read the linked behavior notes for units, age and known conflicts.']
    for t in tables:
        article = by_id[t['source_article_id']]
        path = Path(t['destination'])
        source = sources.get(article.get('source_revision_id',article['id']))
        output[path] = render_table(t, article, source)
        for table in t['tables']:
            if table.get('destination'):
                output[Path(table['destination'])] = render_table_part(t, article, table, source)
        index += [f"- [{t['title']}]({link_from(BASE/'index.md', t['destination'])}) — source {article['id']}, edited {article['source_updated_at'][:10]}."]
    output[BASE/'index.md'] = '\n\n'.join(index)+'\n'
    output.update(render_archive(snapshot, data))
    output.update(render_source_routes(data))
    output[Path('coverage/wiki-coverage.json')] = coverage(data, tables)
    return output


def render_source_routes(data):
    """Route guide readers to changed source facts before using copied prose."""
    begin, end = '<!-- wiki-source-updates:start -->', '<!-- wiki-source-updates:end -->'
    updated = {str(alias):a for a in data['articles'] if a.get('source_backed')
               for alias in set(a.get('revision_ids', [])) | {a['id']}}
    output = {}
    for path in sorted((ROOT/'skills').glob('*/references/*.md')):
        original = path.read_text(encoding='utf-8')
        body = re.sub(re.escape(begin)+r'.*?'+re.escape(end)+r'\n*', '', original, flags=re.S)
        ids = re.findall(r'\]\([^\n)]*wiki/(?:articles|tables|archive)/(\d+)(?:\.md|/)',body)
        records = {updated[i]['id']:updated[i] for i in ids if i in updated}
        if records:
            lines = [begin, '## Current wiki sources',
                     'Before using facts or values covered by these sources, read the corresponding current article. Its text takes precedence over copied details below; use this guide for the overall pattern.']
            relative = path.relative_to(ROOT)
            for article in sorted(records.values(),key=lambda a:a['title']):
                revision = article['id'] if article.get('source_missing') else article.get('source_revision_id',article['id'])
                target = BASE/'archive'/f'{revision}.md'
                lines.append(f"- [{article['title']}]({link_from(relative,target)})")
            lines.append(end)
            title, separator, remainder = body.partition('\n')
            body = title+'\n\n'+'\n\n'.join(lines)+'\n\n'+remainder.lstrip('\n')
        if records or body != original:
            output[path.relative_to(ROOT)] = body
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files differ; write nothing.')
    args = parser.parse_args()
    try:
        data = load('sources/wiki-content.json')
        snapshot = load('sources/wiki-articles.json')
        tables = [json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT/'sources/wiki-tables').glob('*.json'))]
        validate(data, tables)
        validate_snapshot(snapshot, load('sources/wiki-index.json'))
        output = render(data, tables, snapshot)
    except (KeyError, ValueError, OSError) as exc:
        print(f'Wiki generation failed: {exc}', file=sys.stderr); return 1
    changed = []
    for path, content in output.items():
        target = ROOT/path
        if not target.exists() or target.read_text(encoding='utf-8') != content:
            changed.append(str(path))
            if not args.check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding='utf-8')
    # A renamed topic must not leave stale claims in the public skill.
    stale = [p for p in (ROOT/BASE).rglob('*.md') if p.relative_to(ROOT) not in output and p.read_text(encoding='utf-8').startswith(GENERATED)]
    if args.check:
        if changed or stale:
            print('Out-of-date wiki outputs:\n'+'\n'.join(changed+[str(p.relative_to(ROOT)) for p in stale])); return 1
    else:
        for p in stale: p.unlink()
    print(f"Wiki {'checked' if args.check else 'generated'}: {len(data['articles'])} articles, {sum(len(a['notes']) for a in data['articles'])} notes, {len(tables)} table files, {len(output)} outputs.")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
